### PR TITLE
Issue #11: add explanation texts

### PR DESCRIPTION
**Pull request by geirkairam**
add info boxes and translations.

### CODE REVIEW

**Comment by andrenarchy** [comment]
Can you rebase this branch on master?

**Comment by geirkairam** [comment]
mhh... I'm not sure I did this rebasing right...

**Comment by andrenarchy** [comment]
I rebased your commit on master. Usually a `git rebase master` is sufficient. If the rebase fails, you have to fix things manually...

Is this PR ready for merging? :smile:

**Comment by geirkairam** [comment]
i don't get this rebase stuff completely :P so yes I guess if it works for you it's ready for merge

**Comment by andrenarchy** [comment]
@geirkairam: are these the texts that Monic wrote?

**Comment by andrenarchy** [comment]
I improved the English texts a little bit. I suggest that we first get English right and then translate it to German when we're satisfied. We're still in an early phase where a lot of descriptions move and updating 2 languages feels cumbersome currently. OK?

I'm very happy with the (English) texts in this PR but I think that the presentation can be improved significantly. Maybe we should have another meeting where we improve this?

**Comment by geirkairam** [comment]
No the texts are mine. I did'nt know there are texts from Monic. I agree with another meeting for these text. What improvements do you have in mind?

**Comment by andrenarchy** [comment]
Some help texts should always be visible and not only when the corresponding checkbox is active. Example:
screenshot from 2015-10-18 12 04 02

Furthermore, the help texts clutter the form which probably impairs usability. Example:
screenshot from 2015-10-18 12 02 53

Showing the help texts below input fields would improve things in my opinion. Here's a beautiful form from airbnb:
screenshot from 2015-10-18 12 01 28

@geirkairam I'll give it a shot now and update this PR, OK?

**Comment by geirkairam** [comment]
go for it :)

**Comment by andrenarchy** [comment]
I restyled only the section _IP addresses_. What do you think?

Screenshot without IP fields:
screenshot from 2015-10-18 14 43 32

Screenshot with IP fields:
screenshot from 2015-10-18 14 43 47

**Comment by geirkairam** [comment]
yay I like it

**Comment by geirkairam** [comment]
I think this can be merged now. @andrenarchy @k-nut what do you think?

**Comment by k-nut** [comment]
+1

**Comment by andrenarchy** [comment]
I added a few validations and fixed a few styling issues. Since everybody is happy, I'll merge this one.

Thanks @geirkairam for the good work!

**Pull request merged**
